name: Deploy Docusaurus to GitHub Pages

# This workflow runs when:
# 1. Code is pushed to the main branch
# 2. The workflow is manually triggered (via GitHub UI)
on:
  push:
    branches: [main]
  workflow_dispatch:

# Define job concurrency to prevent overlapping deployments
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Give the workflow write permissions to the repository content
# This is needed for the peaceiris/actions-gh-pages action to push changes
permissions:
  contents: write

# Environment setup
env:
  NODE_VERSION: '18' # LTS version for better stability

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Set timeout to prevent hung builds
    
    steps:
      # Checkout repository with a small history to speed up checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      # Setup Node.js with caching for faster builds
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      # Install dependencies with clean install for reproducible builds
      - name: Install dependencies
        run: npm ci
        timeout-minutes: 5
      
      # Build the Docusaurus site
      - name: Build
        run: DISABLE_BROKEN_LINKS_CHECK=true npm run build
        timeout-minutes: 5
      
      # Deploy to GitHub Pages using peaceiris/actions-gh-pages
      # This action commits the built files to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # Enable the following options to keep commit history clean
          force_orphan: true # Use a single-commit history for gh-pages branch
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy documentation site: ${{ github.event.head_commit.message }}'
      
      # Report success
      - name: Output success message
        if: success()
        run: |
          echo "🚀 Successfully deployed to https://nocoderoi.github.io/bubble-documentation/"

